<?php
/**
 * Hyvä Themes - https://hyva.io
 * Copyright © Hyvä Themes 2020-present. All rights reserved.
 * This product is licensed per Magento install
 * See https://hyva.io/license
 */

declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\ProductAttributes;
use Hyva\Theme\ViewModel\ProductCompare;
use Hyva\Theme\ViewModel\ProductPage;
use Hyva\Theme\ViewModel\Wishlist;
use Magento\Catalog\Model\Product;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */

/** @var ProductPage $productViewModel */
$productViewModel = $viewModels->require(ProductPage::class);
/** @var ProductAttributes $attributesViewModel */
$attributesViewModel = $viewModels->require(ProductAttributes::class);
/** @var Product $product */
$product = $productViewModel->getProduct();
$productType = $product->getTypeId();

$currentProduct = $block->getCurrentProduct();

?>
<div class="w-full mb-6">
    <div class="my-2 flex">
        <?= $block->getChildHtml('product.info.review') ?>
    </div>

    <?php if ($shortDescription = $productViewModel->getShortDescription()) { ?>
        <div class="mb-4 leading-relaxed product-description hidden prose"><?= /* @noEscape */ $shortDescription ?></div>
    <?php } ?>

    <div class="flex flex-col sm:flex-row justify-between my-4">
        <?= $block->getChildHtml("product.info.stockstatus") ?>
        <?= $block->getChildHtml("alert.urls") ?>
    </div>

    <?= $block->getChildHtml('product.info.form') ?>

    <div class="">

        <div class="flex mt-4 ml-auto sm:mt-0">
            <?php if ($product->isSaleable()): ?>
                <?= $block->getChildHtml("product.info.quantity") ?>
                <?= $block->getChildHtml("product.info.addtocart") ?>
            <?php endif; ?>
        </div>

        <?php if ($productType === 'bundle'): ?>
            <span class="sr-only">
                <?= $escaper->escapeHtml(__('The price depends on the chosen options')) ?>
            </span>
        <?php endif; ?>

        <div class="border-b pb-6" role="group" aria-label="<?= $escaper->escapeHtmlAttr('Price') ?>">
            <?= $block->getChildHtml("product.info.price") ?>
            <div class="flex">
                <?= $block->getChildHtml('product.info.addtowishlist'); ?>
                <?= $block->getChildHtml('product.info.addtocompare'); ?>
                <?= $block->getChildHtml('product.info.emailtofriend'); ?>
                <?= $block->getChildHtml('product.info.additional.actions'); ?>
            </div>
        </div>

    </div>

    <div class="katapult-catalog-product-view-pre-approved pt-3">
        <div class="katapult-product-detail-logo"></div>
        <div class="katapult-product-detail-logo-text-right">
            <?= /* @noEscape */ __('No credit? Shop now. Pay over time.') ?>
            <a href="<?= $currentProduct ?>"><?= /* @noEscape */ __('Get pre-approved') ?></a>
        </div>
        <div id="als_pdp" data-amount="240880.00000000003" class="affirm-as-low-as w-full flex pt-2" data-page-type="product" data-affirm-color="blue" data-learnmore-show="true" style="visibility: visible;">Starting at <span class="affirm-ala-price">$117</span>/mo or 0% APR with <span class="__affirm-logo __affirm-logo-blue __ligature__affirm_full_logo__ __processed">Affirm</span>. <a class="affirm-modal-trigger" aria-label="See if you qualify - Learn more about Affirm Financing (opens in modal)" href="javascript:void(0)"> See if you qualify</a></div>
    </div>

    <div>
    <dl id="product-details">
        <?php foreach ($block->getAttributes() as $attributeConfig):
            $attribute = $attributesViewModel->getAttributeFromLayoutConfig($attributeConfig); ?>
            <?php if ($value = $attribute['value'] ?? null): ?>
            <div class="w-full flex border-gray-300 pb-6 my-6 last:border-b <?=/* @noEscape */ $attribute['value'] ?: "" ?>">
                <dt class="text-left text-gray-700 product-detail-label">
                    <?= $escaper->escapeHtml($attribute['label']) ?>:
                </dt>
                <dd class="pl-6 text-left text-gray-900 product-detail-value">
                    <?= $escaper->escapeHtml($value) ?>
                </dd>
            </div>
        <?php endif ?>
        <?php endforeach; ?>
    </dl>
    </div>
    <?php if ($product->isSaleable()): ?>
        <div class="flex mt-4 justify-end">
            <?= $block->getChildHtml('addtocart.shortcut.buttons') ?>
        </div>
    <?php endif; ?>

    <?php if ($tierPriceBlock = $block->getChildHtml("product.price.tier")): ?>
        <div class="py-4 my-2 tier-price-container">
            <?= /** @noEscape */ $tierPriceBlock ?>
        </div>
    <?php endif; ?>

    <?= $block->getChildHtml("product.info.additional") ?>
</div>
